# Generated by Django 2.0 on 2018-06-25 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='fko_user',
            field=models.OneToOneField(db_column='fk_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
